##############################
# Country definition for ALB #
##############################

#####################
# Country main data #
#####################

country = {
  tag                = ALB
  name               = "Albanian Kingdom"
  capital            = 0 # (Embarked)
  manpower           = 0
  # Resource Reserves
  energy         = 0
  metal          = 0
  rare_materials = 0
  oil            = 0
  supplies       = 0
  money          = 0

  nationalprovinces      = { }
  ownedprovinces         = { }
  controlledprovinces    = { }
}
