##############################
# Country definition for U62 #
##############################

#####################
# Country main data #
#####################

country = {
  tag                = U62
  capital            = 0 # (Embarked)
  manpower           = 0
  # Resource Reserves
  energy         = 0
  metal          = 0
  rare_materials = 0
  oil            = 0
  supplies       = 0
  money          = 0

  nationalprovinces      = { 1165 1069 1166 1162 1167 1169 1168 1161 1163 1164 1070 }
  ownedprovinces         = { 1162 1166 1069 1165 1164 1070 1163 1161 1167 1169 1168 }
  controlledprovinces    = { 1162 1166 1070 1164 1165 1069 1163 1161 1168 1169 1167 }
}
