##############################
# Country definition for UER #
##############################

#####################
# Country main data #
#####################

country = {
  tag                = UER
  capital            = 0 # (Embarked)
  manpower           = 0
  # Resource Reserves
  energy         = 0
  metal          = 0
  rare_materials = 0
  oil            = 0
  supplies       = 0
  money          = 0

  nationalprovinces      = { 1131 1133 1132 690 1134 667 664 }
  ownedprovinces         = { 1131 1133 1134 690 664 667 1132 }
  controlledprovinces    = { 1131 1133 1134 690 664 667 1132 }
}
