##############################
# Country definition for UGS #
##############################

#####################
# Country main data #
#####################

country = {
  tag                = UGS
  capital            = 0 # (Embarked)
  manpower           = 0
  # Resource Reserves
  energy         = 0
  metal          = 0
  rare_materials = 0
  oil            = 0
  supplies       = 0
  money          = 0

  nationalprovinces      = { 680 681 685 544 688 686 689 }
  ownedprovinces         = { 685 544 681 680 686 689 688 }
  controlledprovinces    = { 685 686 689 688 544 681 680 }
}
