province = {
  id = 1 # Reykjavik
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 200
}

province = {
  id = 5 # Scapa Flow
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 3 current_size = 3 }
}

province = {
  id = 6 # Inverness
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 7 # Aberdeen
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 8 # Fort William
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 10 # Dumfries
  anti_air = 2
  air_base = { size = 8 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 11 # Glasgow
  ic = 4
  radar_station = { size = 3 current_size = 3 }
}

province = {
  id = 12 # Edinburgh
  ic = 4
  radar_station = { size = 4 current_size = 4 }
}

province = {
  id = 13 # Sunderland
  ic = 7
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  radar_station = { size = 4 current_size = 4 }
}

province = {
  id = 14 # Carlisle
  ic = 3
  radar_station = { size = 3 current_size = 3 }
}

province = {
  id = 17 # Manchester
  ic = 8
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 18 # Sheffield
  ic = 8
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  radar_station = { size = 6 current_size = 6 }
}

province = {
  id = 19 # Bristol
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  radar_station = { size = 5 current_size = 5 }
}

province = {
  id = 20 # Exeter
  anti_air = 6
  air_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 22 # Cardiff
  radar_station = { size = 4 current_size = 4 }
}

province = {
  id = 23 # Plymouth
  coastalfort = 1
  anti_air = 6
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 7 current_size = 7 }
}

province = {
  id = 24 # Birmingham
  ic = 9
  anti_air = 2
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 25 # Norwich
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 7 current_size = 7 }
}

province = {
  id = 26 # Dover
  coastalfort = 3
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 8 current_size = 8 }
}

province = {
  id = 27 # Portsmouth
  anti_air = 6
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 8 current_size = 8 }
}

province = {
  id = 28 # Oxford
  anti_air = 2
  radar_station = { size = 2 current_size = 2 }
  nuclear_reactor = 4
}

province = {
  id = 29 # London
  ic = 9
  anti_air = 3
  radar_station = { size = 4 current_size = 4 }
  supplypool = 1000
  oilpool = 1000
}

province = {
  id = 34 # Dublin
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 36 # Belfast
  air_base = { size = 8 current_size = 8 }
  naval_base = { size = 3 current_size = 3 }
  radar_station = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 37 # Brest
  ic = 3
  coastalfort = 2
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 39 # Lorient
  ic = 2
  landfort = 8
  coastalfort = 1
  naval_base = { size = 6 current_size = 6 }
  supplypool = 100
  oilpool = 50
}

province = {
  id = 40 # Saint-Nazaire
  anti_air = 2
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 43 # Cherbourg
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 44 # Caen
  coastalfort = 4
  anti_air = 1
}

province = {
  id = 46 # Bayeux
  coastalfort = 2
  supplypool = 4500
  oilpool = 2000
}

province = {
  id = 49 # Calais
  coastalfort = 4
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 51 # Dunkirk
  landfort = 8
  coastalfort = 4
  naval_base = { size = 3 current_size = 3 }
  radar_station = { size = 1 current_size = 1 }
  supplypool = 100
  oilpool = 50
}

province = {
  id = 52 # Lille
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 53 # Dieppe
  coastalfort = 4
  anti_air = 2
}

province = {
  id = 55 # Paris
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
  nuclear_reactor = 2
}

province = {
  id = 57 # Nantes
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 58 # Le Mans
  ic = 1
}

province = {
  id = 63 # Auxerre
  ic = 2
}

province = {
  id = 66 # Orleans
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 68 # Bordeaux
  coastalfort = 2
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 69 # La Rochelle
  landfort = 8
  coastalfort = 2
  anti_air = 4
  naval_base = { size = 6 current_size = 6 }
  supplypool = 100
  oilpool = 50
}

province = {
  id = 72 # Chateauroux
  anti_air = 1
}

province = {
  id = 74 # Vichy
  anti_air = 1
}

province = {
  id = 77 # Toulouse
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 82 # Montpellier
  coastalfort = 4
}

province = {
  id = 86 # Toulon
  anti_air = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 87 # Nice
  landfort = 2
}

province = {
  id = 89 # Marseille
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 90 # Grenoble
  landfort = 1
}

province = {
  id = 91 # Chambery
  landfort = 1
}

province = {
  id = 94 # Corsica
  supplypool = 500
}

province = {
  id = 96 # Longwy
  landfort = 1
}

province = {
  id = 104 # Metz
  ic = 1
  landfort = 3
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 105 # Colmar
  ic = 1
  landfort = 3
  anti_air = 2
}

province = {
  id = 107 # Strasbourg
  ic = 1
  landfort = 3
  anti_air = 2
}

province = {
  id = 108 # Liege
  landfort = 2
  anti_air = 2
}

province = {
  id = 113 # Namur
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 114 # Bruges
  coastalfort = 2
  anti_air = 1
  naval_base = { size = 3 current_size = 3 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 115 # Antwerpen
  anti_air = 2
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 116 # Brussels
  anti_air = 1
  air_base = { size = 6 current_size = 6 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 118 # Eindhoven
  anti_air = 2
}

province = {
  id = 122 # Amsterdam
  coastalfort = 2
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 124 # Groningen
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 125 # Rotterdam
  anti_air = 2
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 126 # Aachen
  landfort = 2
  anti_air = 2
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 127 # Saarbrucken
  landfort = 3
  anti_air = 2
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 128 # Trier
  landfort = 1
  anti_air = 1
}

province = {
  id = 129 # Koblenz
  landfort = 2
  anti_air = 2
}

province = {
  id = 130 # Mainz
  landfort = 3
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 131 # Cologne
  landfort = 2
  anti_air = 2
  radar_station = { size = 4 current_size = 4 }
}

province = {
  id = 132 # Freiburg
  landfort = 3
  anti_air = 2
}

province = {
  id = 134 # Stuttgart
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 137 # Kassel
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 138 # Frankfurt/Main
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 141 # Muenster
  anti_air = 2
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 142 # Duesseldorf
  anti_air = 3
}

province = {
  id = 144 # Bielefeld
  anti_air = 3
  radar_station = { size = 4 current_size = 4 }
}

province = {
  id = 145 # Essen
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  radar_station = { size = 4 current_size = 4 }
}

province = {
  id = 146 # Hannover
  anti_air = 2
  radar_station = { size = 3 current_size = 3 }
}

province = {
  id = 147 # Wilhelmshaven
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 148 # Bremen
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 151 # Lubeck
  anti_air = 1
}

province = {
  id = 152 # Kiel
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 153 # Rostock
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 154 # Hamburg
  anti_air = 2
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 155 # Stolp
  landfort = 2
}

province = {
  id = 158 # Stettin
  landfort = 2
}

province = {
  id = 161 # Deutsch Krone
  landfort = 4
}

province = {
  id = 163 # Berlin
  ic = 1
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 167 # Breslau
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 169 # Magdeburg
  anti_air = 2
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 170 # Leipzig
  ic = 5
  anti_air = 1
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 173 # Dresden
  air_base = { size = 3 current_size = 3 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 177 # Nuremberg
  anti_air = 1
}

province = {
  id = 179 # Munich
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 181 # Danzig
  ic = 5
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 184 # Koenigsberg
  landfort = 4
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 189 # Innsbruck
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 191 # Klagenfurt
  anti_air = 1
}

province = {
  id = 195 # Vienna
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 196 # Brno
  anti_air = 2
}

province = {
  id = 207 # Prague
  anti_air = 2
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 208 # Bratislava
  ic = 5
  anti_air = 1
}

province = {
  id = 214 # Presov
  ic = 3
}

province = {
  id = 218 # Frederikshavn
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 222 # Torun
  anti_air = 2
}

province = {
  id = 223 # Lodz
  province_revoltrisk = 8
}

province = {
  id = 224 # Poznan
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 225 # Bydgoszcz
  anti_air = 1
}

province = {
  id = 226 # Gdynia
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 227 # Czestochowa
  anti_air = 3
  air_base = { size = 3 current_size = 3 }
  province_revoltrisk = 8
}

province = {
  id = 228 # Siedlce
  ic = 3
  air_base = { size = 3 current_size = 3 }
  province_revoltrisk = 8
}

province = {
  id = 229 # Ostroleka
  province_revoltrisk = 8
}

province = {
  id = 230 # Plock
  anti_air = 1
  province_revoltrisk = 8
}

province = {
  id = 231 # Wloclawek
  province_revoltrisk = 8
}

province = {
  id = 232 # Warsaw
  ic = 2
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
  province_revoltrisk = 8
}

province = {
  id = 233 # Sosnowiec
  province_revoltrisk = 8
}

province = {
  id = 234 # Radom
  province_revoltrisk = 8
}

province = {
  id = 235 # Krakow
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  province_revoltrisk = 8
}

province = {
  id = 236 # Nowy Sacz
  province_revoltrisk = 8
}

province = {
  id = 237 # Tarnow
  province_revoltrisk = 8
}

province = {
  id = 240 # Tarnopol
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 242 # Lwow
  ic = 1
}

province = {
  id = 243 # Lublin
  province_revoltrisk = 8
}

province = {
  id = 246 # Chelm
  province_revoltrisk = 8
}

province = {
  id = 247 # Brest-Litovsk
  ic = 1
  landfort = 3
}

province = {
  id = 252 # Suwalki
  anti_air = 1
  province_revoltrisk = 8
}

province = {
  id = 261 # Klaipeda
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 262 # Kaunas
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 264 # Riga
  ic = -3
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 268 # Liepaja
  landfort = 6
  anti_air = 2
}

province = {
  id = 269 # Jelgava
  landfort = 8
  anti_air = 4
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
  supplypool = 1000
  oilpool = 500
}

province = {
  id = 270 # Tallinn
  ic = -3
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 277 # Pecs
  ic = 2
}

province = {
  id = 281 # Debrecen
  ic = 2
}

province = {
  id = 284 # Budapest
  ic = 2
  landfort = 8
  anti_air = 2
  air_base = { size = 8 current_size = 8 }
}

province = {
  id = 294 # Copenhagen
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 306 # Ismail
  anti_air = 1
}

province = {
  id = 307 # Dobrich
  ic = 1
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 310 # Constantza
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 311 # Ploesti
  ic = 7
  anti_air = 6
}

province = {
  id = 316 # Bucharest
  anti_air = 2
  air_base = { size = 5 current_size = 5 }
}

province = {
  id = 321 # Sofia
  ic = 2
  anti_air = 2
}

province = {
  id = 322 # Gabrovo
  ic = 1
}

province = {
  id = 323 # Pleven
  ic = 1
}

province = {
  id = 325 # Burgas
  ic = 2
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 327 # Krusevac
  province_revoltrisk = 10
}

province = {
  id = 328 # Kumanovo
  province_revoltrisk = 10
}

province = {
  id = 329 # Pristina
  province_revoltrisk = 10
}

province = {
  id = 330 # Nis
  air_base = { size = 1 current_size = 1 }
  province_revoltrisk = 10
}

province = {
  id = 331 # Pirot
  province_revoltrisk = 10
}

province = {
  id = 332 # Cetinje
  naval_base = { size = 3 current_size = 3 }
  province_revoltrisk = 10
}

province = {
  id = 333 # Skopje
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  province_revoltrisk = 10
}

province = {
  id = 334 # Tetovo
  province_revoltrisk = 10
}

province = {
  id = 335 # Prijepolje
  province_revoltrisk = 10
}

province = {
  id = 336 # Petrovgrad
  province_revoltrisk = 10
}

province = {
  id = 337 # Ruma
  province_revoltrisk = 10
}

province = {
  id = 338 # Belgrade
  anti_air = 3
  air_base = { size = 6 current_size = 6 }
  province_revoltrisk = 10
}

province = {
  id = 339 # Bor
  province_revoltrisk = 10
}

province = {
  id = 340 # Sabac
  province_revoltrisk = 10
}

province = {
  id = 342 # Uzice
  province_revoltrisk = 10
}

province = {
  id = 343 # Dubrovnik
  anti_air = 2
  province_revoltrisk = 10
}

province = {
  id = 344 # Osijek
  province_revoltrisk = 10
}

province = {
  id = 345 # Bjelovar
  province_revoltrisk = 10
}

province = {
  id = 346 # Maribor
  province_revoltrisk = 10
}

province = {
  id = 347 # Karlovac
  province_revoltrisk = 10
}

province = {
  id = 348 # Gibraltar
  landfort = 6
  anti_air = 6
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 349 # Ljubljana
  air_base = { size = 1 current_size = 1 }
  province_revoltrisk = 10
}

province = {
  id = 350 # Split
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 3 current_size = 3 }
  province_revoltrisk = 10
}

province = {
  id = 351 # Knin
  province_revoltrisk = 10
}

province = {
  id = 352 # Zagreb
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 353 # Banja Luka
  air_base = { size = 1 current_size = 1 }
  province_revoltrisk = 10
}

province = {
  id = 354 # Tuzla
  province_revoltrisk = 10
}

province = {
  id = 355 # Sarajevo
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  province_revoltrisk = 10
}

province = {
  id = 356 # Mostar
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  province_revoltrisk = 10
}

province = {
  id = 357 # Bihac
  province_revoltrisk = 10
}

province = {
  id = 358 # Travnik
  province_revoltrisk = 10
}

province = {
  id = 359 # Tirana
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  province_revoltrisk = 10
}

province = {
  id = 360 # Korce
  province_revoltrisk = 10
}

province = {
  id = 361 # Shkoder
  province_revoltrisk = 10
}

province = {
  id = 362 # Vlore
  anti_air = 1
  naval_base = { size = 4 current_size = 4 }
  province_revoltrisk = 10
}

province = {
  id = 365 # Thessaloniki
  landfort = 5
  anti_air = 2
}

province = {
  id = 366 # Kozani
  province_revoltrisk = 8
}

province = {
  id = 367 # Ioannina
  landfort = 5
  province_revoltrisk = 8
}

province = {
  id = 368 # Larissa
  province_revoltrisk = 8
}

province = {
  id = 369 # Metsovo
  landfort = 5
  province_revoltrisk = 8
}

province = {
  id = 370 # Alexandroupoli
  province_revoltrisk = 8
}

province = {
  id = 371 # Kerkyra
  province_revoltrisk = 8
}

province = {
  id = 372 # Patra
  province_revoltrisk = 8
}

province = {
  id = 373 # Corinth
  province_revoltrisk = 8
}

province = {
  id = 374 # Chalcis
  province_revoltrisk = 8
}

province = {
  id = 375 # Levadhia
  province_revoltrisk = 8
}

province = {
  id = 376 # Agrinion
  province_revoltrisk = 8
}

province = {
  id = 377 # Athens
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  province_revoltrisk = 8
}

province = {
  id = 378 # Kalymnos
  coastalfort = 4
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  province_revoltrisk = 8
}

province = {
  id = 379 # Rodos
  anti_air = 1
  supplypool = 500
  province_revoltrisk = 8
}

province = {
  id = 380 # Sitia
  province_revoltrisk = 8
}

province = {
  id = 382 # Irakleio
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 500
  province_revoltrisk = 8
}

province = {
  id = 383 # Mytilene
  province_revoltrisk = 8
}

province = {
  id = 388 # Nicosia
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 389 # Zurich
  ic = 3
  landfort = 5
  anti_air = 3
}

province = {
  id = 390 # Lugano
  ic = 1
  landfort = 4
  anti_air = 3
}

province = {
  id = 391 # Geneva
  ic = 2
  landfort = 5
  anti_air = 3
}

province = {
  id = 392 # Bern
  landfort = 5
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 393 # Brescia
  province_revoltrisk = 6
}

province = {
  id = 394 # Belluno
  province_revoltrisk = 6
}

province = {
  id = 395 # Bergamo
  province_revoltrisk = 6
}

province = {
  id = 396 # Genoa
  ic = 7
  landfort = 4
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  province_revoltrisk = 6
}

province = {
  id = 398 # Turin
  ic = { size = 9 current_size = 9 }
  landfort = 4
  anti_air = 1
  air_base = { size = 8 current_size = 8 }
  province_revoltrisk = 6
}

province = {
  id = 399 # Alessandria
  province_revoltrisk = 6
}

province = {
  id = 400 # Venice
  ic = { size = 4 current_size = 4 }
  coastalfort = 2
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 }
  province_revoltrisk = 6
}

province = {
  id = 401 # Trento
  ic = { size = 2 current_size = 2 }
  province_revoltrisk = 6
}

province = {
  id = 402 # Bolzano
  province_revoltrisk = 6
}

province = {
  id = 403 # Capodistria
  landfort = 2
  province_revoltrisk = 6
}

province = {
  id = 404 # Trieste
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
  province_revoltrisk = 6
}

province = {
  id = 405 # Udine
  province_revoltrisk = 6
}

province = {
  id = 406 # Pola
  landfort = 2
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 6 current_size = 6 }
  province_revoltrisk = 6
}

province = {
  id = 407 # Milan
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 408 # Parma
  ic = { size = 3 current_size = 3 }
  anti_air = 1
  province_revoltrisk = 6
}

province = {
  id = 410 # Florence
  ic = 2
  landfort = 4
  province_revoltrisk = 6
}

province = {
  id = 411 # Bologna
  ic = { size = 5 current_size = 5 }
  landfort = 4
  anti_air = 1
  province_revoltrisk = 6
}

province = {
  id = 412 # Ancona
  landfort = 4
  coastalfort = 1
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  province_revoltrisk = 6
}

province = {
  id = 413 # Livorno
  landfort = 2
  province_revoltrisk = 6
}

province = {
  id = 414 # Perugia
  ic = 3
  landfort = 2
  province_revoltrisk = 6
}

province = {
  id = 416 # Anzio
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 419 # Rome
  ic = { size = 4 current_size = 4 }
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 421 # Naples
  ic = { size = 4 current_size = 4 }
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  supplypool = 5000
  oilpool = 5000
}

province = {
  id = 422 # Taranto
  ic = { size = 5 current_size = 5 }
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 426 # Bari
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 429 # Malta
  coastalfort = 1
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 5 current_size = 5 }
  supplypool = 2000
  oilpool = 2000
}

province = {
  id = 430 # Palermo
  ic = { size = 1 current_size = 1 }
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 433 # Siracuse
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 434 # Cagliari
  coastalfort = 1
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 500
  oilpool = 100
}

province = {
  id = 435 # Sassari
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 436 # Tarragona
  ic = 2
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 440 # Barcelona
  ic = 1
}

province = {
  id = 441 # Coruna
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 443 # Bilbao
  ic = 2
}

province = {
  id = 444 # Oviedo
  ic = 1
}

province = {
  id = 451 # Burgos
  ic = 2
}

province = {
  id = 460 # Madrid
  ic = 3
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 464 # Valencia
  ic = 2
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 470 # Granada
  landfort = 2
  anti_air = 2
}

province = {
  id = 473 # Cadiz
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 474 # Sevilla
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 475 # Palma de Mallorca
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 7 current_size = 7 }
  supplypool = 500
}

province = {
  id = 476 # Lisbon
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 481 # Porto
  anti_air = 1
}

province = {
  id = 483 # Oslo
  coastalfort = 3
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  supplypool = 2000
  oilpool = 500
}

province = {
  id = 491 # Alesund
  coastalfort = 3
  anti_air = 4
  air_base = { size = 5 current_size = 5 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 493 # Trondheim
  coastalfort = 2
  anti_air = 1
}

province = {
  id = 495 # Narvik
  anti_air = 6
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 498 # Pavlodar
  ic = 3
}

province = {
  id = 501 # Kokchetav
  ic = 2
}

province = {
  id = 503 # Karaganda
  ic = 2
}

province = {
  id = 504 # Alma-Ata
  ic = 5
}

province = {
  id = 506 # Taldy-Kurgan
  ic = 2
}

province = {
  id = 512 # Pori
  ic = 1
}

province = {
  id = 514 # Kemijarvi
  landfort = 1
}

province = {
  id = 517 # Petsamo
  landfort = 1
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 518 # Suomussalmi
  landfort = 1
}

province = {
  id = 520 # Oulu
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 521 # Vaasa
  ic = 1
}

province = {
  id = 523 # Kajaani
  landfort = 1
}

province = {
  id = 524 # Turku
  ic = 1
  coastalfort = 2
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 525 # Helsinki
  coastalfort = 1
  anti_air = 3
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 526 # Ahvenanmaa
  coastalfort = 1
}

province = {
  id = 527 # Tampere
  anti_air = 2
  air_base = 4
}

province = {
  id = 528 # Mikkeli
  landfort = 1
  anti_air = 2
  air_base = 5
}

province = {
  id = 529 # Kouvola
  landfort = 1
  anti_air = 1
}

province = {
  id = 531 # Viipuri
  landfort = 8
  coastalfort = 2
  anti_air = 4
  air_base = 1
}

province = {
  id = 532 # Sortavala
  anti_air = 6
}

province = {
  id = 533 # Joensuu
  landfort = 1
}

province = {
  id = 534 # Kola
  ic = 1
}

province = {
  id = 535 # Murmansk
  ic = 1
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 542 # Arkhangelsk
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 553 # Leningrad
  ic = 2
  landfort = 5
  coastalfort = 5
  anti_air = 6
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 561 # Staraya Russa
  anti_air = 1
}

province = {
  id = 563 # Torzhok
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 566 # Pskov
  air_base = { size = 6 current_size = 6 }
}

province = {
  id = 572 # Moscow
  ic = 3
  landfort = 5
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 576 # Kaluga
  ic = -1
}

province = {
  id = 577 # Nelidovo
  rocket_test = 5
}

province = {
  id = 584 # Tula
  ic = 1
}

province = {
  id = 585 # Kozelsk
  anti_air = 1
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 587 # Klintsy
  anti_air = 2
}

province = {
  id = 588 # Bryansk
  air_base = { size = 4 current_size = 3 }
}

province = {
  id = 589 # Smolensk
  ic = 1
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 590 # Vitebsk
  ic = -1
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 597 # Luban
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 599 # Minsk
  ic = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 600 # Mogilev
  air_base = { size = 8 current_size = 8 }
}

province = {
  id = 601 # Gomel
  ic = -1
}

province = {
  id = 604 # Kursk
  air_base = { size = 5 current_size = 5 }
}

province = {
  id = 611 # Zhitomir
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 617 # Kiev
  ic = 1
  anti_air = 3
  air_base = { size = 8 current_size = 8 }
}

province = {
  id = 622 # Nikolayev
  ic = -1
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 626 # Odessa
  ic = 1
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 627 # Krivoy Rog
  ic = -1
}

province = {
  id = 628 # Kirovograd
  air_base = { size = 2 current_size = 1 }
}

province = {
  id = 629 # Poltava
  ic = -1
  anti_air = 2
}

province = {
  id = 630 # Zaporozhye
  ic = -1
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 631 # Mariupol
  ic = -1
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 632 # Dnepropetrovsk
  ic = -2
}

province = {
  id = 636 # Kharkov
  ic = -1
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 639 # Dzhankoy
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 640 # Kerch
  ic = 1
}

province = {
  id = 641 # Sevastopol
  ic = 1
  landfort = 3
  coastalfort = 5
  anti_air = 6
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 644 # Rostov-on-Don
  ic = 2
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 648 # Rossosh
  anti_air = 1
}

province = {
  id = 653 # Pavlovsk
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 654 # Voronezh
  air_base = { size = 2 current_size = 1 }
}

province = {
  id = 663 # Stalingrad
  ic = 2
  landfort = 5
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 666 # Balakowo
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 668 # Kuybyshev
  ic = 1
}

province = {
  id = 669 # Saratov
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 679 # Murom
  ic = 2
}

province = {
  id = 682 # Ivanovo
  ic = 2
}

province = {
  id = 683 # Arzamas
  nuclear_reactor = 6
}

province = {
  id = 691 # Krasnodar
  ic = -1
}

province = {
  id = 694 # Novorossiysk
  ic = 1
}

province = {
  id = 706 # Astrakhan
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 708 # Kutaisi
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 709 # Tbilisi
  ic = 3
}

province = {
  id = 711 # Yerevan
  ic = 2
}

province = {
  id = 713 # Baku
  ic = 2
}

province = {
  id = 715 # Tangier
  air_base = { size = 2 current_size = 2 }
  supplypool = 500
}

province = {
  id = 717 # Rabat
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 718 # Casablanca
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 727 # Algiers
  anti_air = 2
  naval_base = { size = 2 current_size = 2 }
  supplypool = 3000
  oilpool = 2000
}

province = {
  id = 728 # Oran
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 729 # Tlemcen
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 739 # Colomb Bechar
  rocket_test = 2
}

province = {
  id = 744 # Gabes
  landfort = 5
}

province = {
  id = 745 # Sousse
  landfort = 3
}

province = {
  id = 747 # Tunis
  landfort = 3
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 748 # Bizerte
  landfort = 3
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 750 # Tripoli
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 761 # Benghazi
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 765 # Tobruk
  landfort = 6
  coastalfort = 2
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 787 # Cairo
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 789 # Alexandria
  anti_air = 5
  air_base = { size = 7 current_size = 7 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 791 # Port Said
  anti_air = 2
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 810 # Khartoum
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 815 # Massawa
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 816 # Assab
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 825 # Addis Adeba
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 827 # Gode
  landfort = 1
}

province = {
  id = 828 # Harer
  landfort = 1
}

province = {
  id = 833 # Djibouti
  anti_air = 1
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 836 # Mogadishu
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 838 # Kismayo
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 842 # Mombasa
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 856 # Maxixe
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 872 # Durban
  anti_air = 3
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 876 # Johannesburg
  ic = 2
  anti_air = 3
}

province = {
  id = 880 # Cape Town
  ic = 2
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 881 # Port Elizabeth
  anti_air = 1
}

province = {
  id = 882 # Swakopmund
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 889 # Balboa
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 892 # Lobito
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 893 # Cabinda
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 894 # Matadi
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 900 # Suez
  anti_air = 2
  naval_base = { size = 1 current_size = 1 }
  supplypool = 2000
  oilpool = 1000
}

province = {
  id = 907 # Brazzaville
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 912 # Sao Tome
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 915 # Libreville
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 917 # Pointe-Noire
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 929 # Lagos
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 956 # Accra
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 962 # Abidjan
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 963 # Bissau
  anti_air = 2
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 964 # Freetown
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 969 # Monrovia
  anti_air = 1
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 978 # Dakar
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 988 # Villa Cisneros
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 990 # Las Palmas de Gran Canaria
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 992 # Cape Verde
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 995 # The Azores
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1002 # Tamatave
  anti_air = 1
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1008 # Tel Aviv
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  province_revoltrisk = 10
}

province = {
  id = 1009 # Gaza
  province_revoltrisk = 10
}

province = {
  id = 1010 # Eilat
  province_revoltrisk = 10
}

province = {
  id = 1011 # Haifa
  province_revoltrisk = 10
}

province = {
  id = 1013 # Akko
  province_revoltrisk = 10
}

province = {
  id = 1019 # Beirut
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1022 # Amman
  province_revoltrisk = 5
}

province = {
  id = 1023 # Irbid
  province_revoltrisk = 5
}

province = {
  id = 1024 # As Zarqa
  province_revoltrisk = 5
}

province = {
  id = 1025 # Ma'an
  province_revoltrisk = 5
}

province = {
  id = 1026 # Al Kerak
  province_revoltrisk = 5
}

province = {
  id = 1032 # Basrah
  anti_air = 2
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1033 # El Hillah
  anti_air = 1
}

province = {
  id = 1035 # Kut
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1048 # Medina
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1052 # Masqat
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1053 # Aden
  anti_air = 1
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1054 # Antakya
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1075 # Ankara
  anti_air = 4
  air_base = { size = 6 current_size = 6 }
}

province = {
  id = 1076 # Izmit
  anti_air = 4
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1091 # Gameroon
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1097 # Ashkhabad
  ic = 2
}

province = {
  id = 1099 # Samarkand
  ic = 2
}

province = {
  id = 1103 # Tashkent
  ic = 3
}

province = {
  id = 1107 # Frunze
  ic = 4
}

province = {
  id = 1124 # Ulaanbaatar
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1129 # Vorkuta
  ic = 1
}

province = {
  id = 1130 # Berezniki
  ic = 5
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1131 # Ufa
  ic = 3
}

province = {
  id = 1132 # Chelyabinsk
  ic = 2
}

province = {
  id = 1134 # Orenburg
  ic = 3
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1137 # Kurgan
  ic = 5
}

province = {
  id = 1138 # Omsk
  ic = 9
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1142 # Novosibirsk
  ic = 12
}

province = {
  id = 1143 # Biysk
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1148 # Tomsk
  ic = 3
}

province = {
  id = 1151 # Sverdlovsk
  ic = 5
}

province = {
  id = 1158 # Minusinsk
  ic = 5
}

province = {
  id = 1162 # Irkutsk
  ic = 1
}

province = {
  id = 1164 # Ust-Kut
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 1169 # Chita
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1172 # Jerusalem
  anti_air = 1
  province_revoltrisk = 10
}

province = {
  id = 1176 # Blagoveshchensk
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1185 # Gavan
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1190 # Khabarovsk
  air_base = { size = 4 current_size = 3 }
}

province = {
  id = 1191 # Vladivostok
  ic = 1
  landfort = 1
  coastalfort = 3
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1194 # Lesozavodsk
  anti_air = 2
}

province = {
  id = 1199 # Harbin
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1219 # Port Arthur
  anti_air = 4
  air_base = { size = 7 current_size = 7 }
  naval_base = { size = 5 current_size = 5 }
  supplypool = 500
  oilpool = 100
}

province = {
  id = 1223 # Wonsan
  ic = 1
}

province = {
  id = 1226 # Ganggye
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1228 # Seoul
  anti_air = 3
}

province = {
  id = 1232 # Busan
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 5000
  oilpool = 100
}

province = {
  id = 1234 # Buna
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1245 # Tangshan
  supplypool = 2000
  oilpool = 500
}

province = {
  id = 1247 # Beijing
  air_base = { size = 5 current_size = 5 }
}

province = {
  id = 1252 # Taiyuan
  ic = -1
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 1255 # Pingliang
  landfort = 3
}

province = {
  id = 1259 # Yan'an
  landfort = 3
}

province = {
  id = 1260 # Yulin
  landfort = 3
}

province = {
  id = 1264 # Lanzhou
  ic = 3
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 1297 # Chengdu
  ic = 8
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 1299 # Chongqing
  ic = 8
}

province = {
  id = 1307 # Huaihua
  ic = 5
}

province = {
  id = 1328 # Qingdao
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1330 # Jinan
  ic = -1
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1337 # Nanjing
  ic = -3
}

province = {
  id = 1338 # Shanghai
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1345 # Hangzhou
  ic = -1
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 1352 # Nanchang
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 1358 # Fuzhou
  air_base = { size = 1 current_size = 1 }
  supplypool = 1000
  oilpool = 100
}

province = {
  id = 1362 # Taipei
  air_base = { size = 8 current_size = 8 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 1000
  oilpool = 100
}

province = {
  id = 1365 # Haikou
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 1000
  oilpool = 100
}

province = {
  id = 1367 # Maoming
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 1369 # Guangzhou
  ic = -3
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 5 current_size = 5 }
  supplypool = 1000
  oilpool = 100
}

province = {
  id = 1371 # Hong Kong
  coastalfort = 1
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1372 # Macao
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1409 # Lashio
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1415 # Rangoon
  ic = 2
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 1000
  oilpool = 100
}

province = {
  id = 1423 # Bangkok
  ic = 1
}

province = {
  id = 1424 # Nakhon Sawan
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1427 # Khon Kaen
  ic = 1
}

province = {
  id = 1432 # Singapore
  coastalfort = 3
  anti_air = 6
  air_base = { size = 8 current_size = 8 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 500
  oilpool = 100
}

province = {
  id = 1442 # Imphal
  anti_air = 2
  air_base = { size = 5 current_size = 5 }
}

province = {
  id = 1447 # Calcutta
  ic = 5
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1459 # Delhi
  ic = 10
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1495 # Trivandrum
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1503 # Mangalore
  ic = 3
}

province = {
  id = 1510 # Kandy
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1511 # Colombo
  coastalfort = 3
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 2000
  oilpool = 1000
}

province = {
  id = 1517 # Bombay
  ic = 4
  anti_air = 3
  air_base = { size = 7 current_size = 7 }
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 1522 # Rajkot
  ic = 3
}

province = {
  id = 1523 # Gwalior
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1525 # Jodhpur
  ic = 3
}

province = {
  id = 1527 # Bikaner
  ic = 3
}

province = {
  id = 1533 # Karachi
  ic = 2
  anti_air = 1
  air_base = { size = 5 current_size = 5 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 1545 # Sapporo
  ic = 3
  anti_air = 6
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 1549 # Sendai
  ic = 6
  anti_air = 6
  air_base = { size = 5 current_size = 5 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 1550 # Yokohama
  anti_air = 6
}

province = {
  id = 1551 # Niigata
  anti_air = 6
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1552 # Tokyo
  ic = 15
  anti_air = 10
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1553 # Osaka
  ic = 10
  anti_air = 10
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1554 # Hiroshima
  ic = 9
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1557 # Nagoya
  ic = 7
  anti_air = 9
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1558 # Kyoto
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1559 # Matsuyama
  ic = 9
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1560 # Nagasaki
  ic = 5
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1563 # Southern Okinawa
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 }
  supplypool = 1000
}

province = {
  id = 1565 # Manila
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 8 current_size = 8 }
  supplypool = 2000
  oilpool = 500
}

province = {
  id = 1566 # Cabanatuan
  anti_air = 4
  air_base = { size = 5 current_size = 5 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1579 # Davao
  air_base = { size = 5 current_size = 5 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1581 # Efate
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 1582 # Espiritu Santo
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
  supplypool = 500
  oilpool = 500
}

province = {
  id = 1586 # Nouvelle-Caledonie
  anti_air = 1
  naval_base = { size = 3 current_size = 3 }
  supplypool = 3000
  oilpool = 2000
}

province = {
  id = 1587 # Bougainville
  naval_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1588 # Santa Isabel
  naval_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1589 # New Georgia
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 3 current_size = 3 }
  supplypool = 1000
  oilpool = 500
}

province = {
  id = 1590 # Lunga
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 2000
  oilpool = 500
}

province = {
  id = 1596 # Hollandia
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 500
  oilpool = 200
}

province = {
  id = 1602 # Lae
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1604 # Popondetta
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1605 # Wewak
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1607 # Port Moresby
  coastalfort = 1
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
  radar_station = { size = 1 current_size = 1 }
  supplypool = 3000
  oilpool = 2000
}

province = {
  id = 1611 # Male
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1617 # Dili
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1624 # Kuching
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1632 # Balikpapan
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 200
  oilpool = 50
}

province = {
  id = 1638 # Bengkulu
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 7 current_size = 7 }
  supplypool = 500
}

province = {
  id = 1647 # Batavia
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 3 current_size = 3 }
  supplypool = 200
}

province = {
  id = 1653 # Soerabaja
  anti_air = 2
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 1659 # Manado
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 3 current_size = 3 }
  supplypool = 100
}

province = {
  id = 1661 # Iwo Jima
  naval_base = { size = 4 current_size = 4 }
  supplypool = 500
}

province = {
  id = 1662 # Chichi Jima
  anti_air = 2
}

province = {
  id = 1663 # Motoyama
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1665 # Ponape
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1666 # Kusaie
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1667 # Truk
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 500
  oilpool = 100
}

province = {
  id = 1668 # Woleai
  anti_air = 3
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 }
  supplypool = 5000
  oilpool = 5000
}

province = {
  id = 1669 # Yap
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1670 # Peleliu
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1672 # Minami Torishima
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1673 # Wake
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 500
}

province = {
  id = 1674 # Bikini
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 1675 # Eniwetok
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 500
}

province = {
  id = 1676 # Kwajalein
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 500
}

province = {
  id = 1677 # Majuro
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1678 # Makin
  coastalfort = 2
  air_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1680 # Tarawa
  coastalfort = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1681 # Wotje
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1682 # Nauru
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 1683 # Guam
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 500
}

province = {
  id = 1685 # Saipan
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 500
}

province = {
  id = 1686 # Pagan
  anti_air = 3
  supplypool = 500
}

province = {
  id = 1687 # Funafuti
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1694 # Collie
  coastalfort = 1
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1697 # Darwin
  coastalfort = 3
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}

province = {
  id = 1704 # Brisbane
  ic = 1
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1705 # Sydney
  ic = 1
  manpower = 1.87
}

province = {
  id = 1706 # Wollongong
  anti_air = 3
}

province = {
  id = 1707 # Canberra
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  manpower = 1.87
}

province = {
  id = 1708 # Melbourne
  ic = 1
  coastalfort = 6
  anti_air = 3
  manpower = 1.87
}

province = {
  id = 1712 # Adelaide
  ic = 1
  anti_air = 1
}

province = {
  id = 1713 # Robe
  anti_air = 2
}

province = {
  id = 1721 # Wellington
  anti_air = 2
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 1724 # Manus
  air_base = { size = 7 current_size = 7 }
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 1725 # Kavieng
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1726 # Rabaul
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 1728 # Suva
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1731 # Apia
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 1733 # Pago Pago
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 1734 # Pearl Harbor
  coastalfort = 1
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 4 current_size = 4 }
  supplypool = 3000
  oilpool = 2000
}

province = {
  id = 1735 # Kauai
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1736 # Hawaii
  air_base = { size = 1 current_size = 1 }
  radar_station = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1737 # Maui
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1738 # Johnston
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 1739 # Midway
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 6 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1743 # Papeete
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 1747 # Palmyra
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1750 # Kanton
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
  supplypool = 500
}

province = {
  id = 1751 # Baker Island
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1771 # The Bahamas
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1773 # The Bermudas
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1776 # Havana
  anti_air = 1
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1778 # Guantanamo Bay Naval Base
  coastalfort = 1
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 1780 # Ciudad Trujillo
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1781 # Port-au-Prince
  anti_air = 1
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1787 # Concord
  ic = 4
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1789 # Boston
  ic = 6
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1791 # Buffalo
  ic = 3
}

province = {
  id = 1792 # Syracuse
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1795 # New York
  ic = 8
  coastalfort = 3
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1796 # Providence
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 1797 # Newark
  ic = 7
}

province = {
  id = 1802 # Altoona
  ic = 2
}

province = {
  id = 1805 # Philadelphia
  ic = 6
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1806 # Pittsburgh
  ic = 5
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1808 # Baltimore
  ic = 8
  coastalfort = 2
  naval_base = { size = 8 current_size = 8 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1809 # Washington
  ic = 4
  coastalfort = 1
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 6 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1812 # Norfolk
  ic = 10
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1820 # Lexington
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1825 # Cleveland
  ic = 3
}

province = {
  id = 1828 # Indianapolis
  ic = 2
}

province = {
  id = 1832 # Chicago
  ic = 5
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 1833 # Saint Louis
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1839 # Milwaukee
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1845 # Detroit
  ic = 10
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1846 # Rochester
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1855 # Fargo
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1859 # Nebraska City
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1874 # Seattle
  ic = 4
  coastalfort = 3
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1878 # Portland
  ic = 2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1886 # San Diego
  ic = 5
  coastalfort = 1
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1887 # Los Angeles
  ic = 3
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1888 # Sacramento
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1889 # San Francisco
  ic = 4
  coastalfort = 1
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}

province = {
  id = 1896 # Salt Lake City
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}

province = {
  id = 1901 # Tucson
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1904 # Albuquerque
  nuclear_reactor = 7
  rocket_test = 3
}

province = {
  id = 1906 # Santa Fe
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1908 # Denver
  ic = 2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1913 # Oklahoma City
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1922 # Corpus Christi
  anti_air = 1
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 1928 # Houston
  coastalfort = 1
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1931 # New Orleans
  ic = 3
  coastalfort = 1
}

province = {
  id = 1940 # Memphis
  ic = 1
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1944 # Mobile
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1948 # Tampa
  coastalfort = 1
}

province = {
  id = 1952 # Jacksonville
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1953 # Miami
  ic = 1
  coastalfort = 1
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1955 # Atlanta
  ic = 1
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1960 # Charleston
  coastalfort = 1
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1962 # Charlotte
  ic = 1
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 1967 # Matamoros
  ic = 1
}

province = {
  id = 1970 # Oaxaca de Juarez
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1972 # Acapulco de Juarez
  anti_air = 1
}

province = {
  id = 1973 # Leon de los Aldama
  anti_air = 1
}

province = {
  id = 1974 # Mexico City
  ic = 1
  anti_air = 2
}

province = {
  id = 1982 # Guadalajara
  ic = 2
}

province = {
  id = 1986 # Barranquilla
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1988 # Maracaibo
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 1991 # Santa Fe de Bogota
  anti_air = 2
}

province = {
  id = 1993 # Caracas
  anti_air = 2
}

province = {
  id = 1997 # Georgetown
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 2016 # Lima
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 2020 # Nuestra Senora de La Paz
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 2023 # Santiago de Chile
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 2040 # Santiago de Guayaquil
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 2042 # San Francisco de Quito
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 2045 # Falkland Islands
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 2047 # Nuestra Senora de la Asuncion
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 2048 # La Plata
  anti_air = 2
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 2050 # Buenos Aires
  anti_air = 3
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 2052 # Montevideo
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 2053 # Mar del Plata
  anti_air = 3
  naval_base = { size = 3 current_size = 6 }
}

province = {
  id = 2057 # Curitiba
  anti_air = 1
}

province = {
  id = 2058 # Porto Alegre
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 2059 # Sao Paulo
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 2067 # Goiania
  anti_air = 2
}

province = {
  id = 2075 # Rio de Janeiro
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 2078 # Ciudad de Panama
  anti_air = 2
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 2079 # San Salvador
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 2080 # Managua
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 2081 # San Jose
  anti_air = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2085 # Tegucigalpa
  anti_air = 1
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 2088 # Ciudad de Guatemala
  anti_air = 1
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 2089 # Vancouver
  ic = 1
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2103 # Edmonton
  oil = 2
}

province = {
  id = 2104 # Calgary
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  oil = 2
}

province = {
  id = 2106 # Winnipeg
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 2108 # Ottawa
  ic = 1
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 2111 # Toronto
  anti_air = 1
}

province = {
  id = 2117 # Quebec
  ic = 1
  anti_air = 4
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2119 # Montreal
  ic = 1
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 2132 # Halifax
  ic = 1
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2137 # St. John's
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2142 # Anchorage
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 2151 # Dutch Harbor
  coastalfort = 1
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 3 current_size = 3 }
  radar_station = { size = 1 current_size = 1 }
  supplypool = 200
}

province = {
  id = 2153 # Gothenburg
  ic = 1
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 2155 # Kalmar
  ic = 2
}

province = {
  id = 2158 # Uppsala
  ic = 2
}

province = {
  id = 2159 # Stockholm
  anti_air = 5
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 2174 # Attu Island
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
  supplypool = 200
}

